### ISSUE TITLE
better cross domain errors

### ISSUE THREAD

**Issue by max-mapper** [iriscouch/browser-request#4]
Given a cross domain request:

```
request({url: "http://pizza.com/api"}, function(e,r,b) {
  console.log(e,r,b)
})
```

`e` and `b` are null

```
request({url: "http://pizza.com/api", json:true}, function(e,r,b) {
  console.log(e,r,b)
})
```

`e` is a JSON parse syntax error and `b` is null

Would it be possible to detect and return an error about the single origin policy?

**Comment by jhs** [comment]
I hit this bug yesterday rewriting the Iris Couch signup. You're on Chrome, right? If you check your console you should see a cross-origin error. And `r.body` will be `""`. I didn't notice what `r.statusCode` and others were.

I prefer to get between the programmer and the XHR object as little as possible (basically just enough to follow the request API) but in this case I'd like to make it an error. Maybe it could have a `.cross_origin` field so you could distinguish that error from other kinds.

Another thing I need to do is check that jQuery cors flag and see exactly impact that has to the underlying XHR object.

The final thing to to to close this bug is identify how the other browsers handle a CORS failure and at least unify that for the browser-request user.

**Comment by jhs** [comment]
@maxogden What is the status of this bug? May I close it, or what do you think? Thanks.

**Comment by max-mapper** [comment]
just tested it, got a nice error!

```
cors: "rejected"
message: "CORS request rejected: http://google.com"
```

looks good to me
