### ISSUE TITLE
provide a way to fully disable logging.

### ISSUE THREAD

**Issue by perezd** [iriscouch/browser-request#7]
This is really annoying when I want to move into a production setting.

**Comment by jhs** [comment]
Yes, this has been nagging me too! There is an attempted failsafe to no-op if the console logger is missing.

Can we clarify exactly what the bug is?
1. Some browsers are not working because `console` is not defined?
2. The failsafe (which replaces `console.log()` etc. with no-op functions) is not working correctly?
3. The whole idea is dangerous and logging should be opt-in?

Frankly I can see an argument for any of these options. What would you prefer, @perezd?

**Comment by perezd** [comment]
Actually I patched this in my branch. I export the logger and allow the caller to redefine it. Should I send you a pull request?
https://github.com/perezd/browser-request/commit/bf519d5586e6c433258ed3e5b2837b2ab905a753

**Comment by jhs** [comment]
Awesome, yes please send a pull req.

**Comment by max-mapper** [comment]
i wish browser request conformed to the unix law of "silence is golden":

```
When a program has nothing surprising to say, it should say nothing
```

e.g. logging should be off by default

**Comment by perezd** [comment]
Agreed. Jason also has a habit of using Log4Js or whatever the hell and it monkey patches console.xxx. I hate that shit.

**Comment by jhs** [comment]
First of all, if the logging activities break any browser, that is a bug. Please let me know.

I still prefer log4js, which no longer automatically monkey-patches console. However I now regret all logger usage in all my libraries. Logging is becoming a pain point.

In my new code, I now have a "log" object (defaults to `console`) and I assume it has the same API as `console`. So I call `.log()`, `.info()`, etc. The programmer can replace that with whatever logger they want, as long as it has the same API.

**Comment by jhs** [comment]
@perezd I believe this issue corresponds with pull request #8 which I merged.
